services:
  - type: web
    name: deadwood-mafia
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
